### PR TITLE
Update opinions list

### PR DESCRIPTION
**Pull request by katrinundfritz**

### CODE REVIEW

**Comment by katrinundfritz** [comment]
@jaynetics I just did copy/paste of the descriptions we have in the betterplace repository. Is there a better way to do it?

**Review by smnscp — APPROVED** [review]

**Comment by fwolfst** [comment]
@katrinundfritz did you add this by hand? I believe it should be autogenerated, but I have no idea how. If you autogenerated, could you point to the doc for that?

**Comment by katrinundfritz** [comment]
> @katrinundfritz did you add this by hand? I believe it should be autogenerated, but I have no idea how. If you autogenerated, could you point to the doc for that?

@fwolfst  I didn't autogenerate it. Was not sure if/how it works.

**Comment by smnscp** [comment]
Here’s [how to publish API docs](https://github.com/betterplace/betterplace/blob/master/doc/api_v4.md#publishing-updates-of-the-public-api-documentation).

**Comment by jaynetics** [comment]
app/models/api_v4/results/donation_result.rb would be the place to put this

**Pull request closed without merging**
